# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on:
  workflow_dispatch:
    inputs:
      module_name:
        description: 'The name of the module directory to build (e.g., module1, my-tool)'
        required: true
        default: 'module1'
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            osname: linux
          - os: macos-latest
            osname: darwin
          - os: windows-latest
            osname: windows

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - uses: nao1215/actions-ebitengine@v0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: '${{ github.event.inputs.module_name }}/go.mod'

    - name: Run Mage
      uses: magefile/mage-action@6f50bbb8ea47d56e62dee92392788acbc8192d0b
      with:
        version: latest
        install-only: true

    - name: Cross build
      run: mage cross ${{ matrix.osname }}
      working-directory: ${{ github.event.inputs.module_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.osname }}
        path: goxz/

  releases:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ${{ github.event.inputs.module_name }}/goxz
    - name: Create Release
      run: mage upload
      working-directory: ${{ github.event.inputs.module_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
